export const demoBooks = [
  {
    id: "b1",
    title: "長安小食記",
    author: "林間客",
    category: ["古代", "種田"],
    wordCount: 680000,
    status: "reading",
    isReadingNow: true,
    isPinned: true,
    addDate: "2026-09-12",
    synopsis:
      "城南的巷尾，新開了一間小食鋪。\n\n一碗熱湯、一盞晚燈，把來往的人留在了長安。她原只想把日子過好，卻在柴米油鹽之間，遇見了許多值得記住的人。",
    review: "",
  },
  {
    id: "b2",
    title: "山海有歸期",
    author: "青嶼",
    category: ["仙俠", "奇幻"],
    wordCount: 1250000,
    status: "reading",
    isReadingNow: true,
    addDate: "2026-09-10",
    synopsis:
      "少年帶著一封沒有收信人的信，走進群山。山海之間，每一次相遇，都是歸途的一部分。",
  },
  {
    id: "b3",
    title: "春日來信",
    author: "南枝",
    category: ["言情", "都市"],
    wordCount: 320000,
    status: "reading",
    addDate: "2026-09-09",
    synopsis: "一封寄錯地址的信，讓兩段平行的生活開始交會。",
  },
  {
    id: "b4",
    title: "霧中的第七封信",
    author: "白石",
    category: ["懸疑", "推理"],
    wordCount: 460000,
    status: "finished",
    rating: 4.5,
    finishDate: "2026-09-08",
    addDate: "2026-08-30",
    synopsis: "小鎮的郵局收到七封匿名信，而寄件日期，都在明天。",
    review:
      "伏筆收得很漂亮，人物的動機也說得通。喜歡結尾留下的一點餘韻，是會想再讀一次的故事。",
  },
  {
    id: "b5",
    title: "在世界盡頭種一座花園",
    author: "微雨",
    category: ["末世", "種田", "奇幻"],
    wordCount: 870000,
    status: "reading",
    addDate: "2026-09-06",
    synopsis: "當城市安靜下來，她決定從一顆種子開始，重新學習生活。",
  },
  {
    id: "b6",
    title: "歲月與你，皆是溫柔",
    author: "江照",
    category: ["都市", "言情"],
    wordCount: 280000,
    status: "finished",
    rating: 4,
    finishDate: "2026-08-28",
    addDate: "2026-08-18",
    review: "步調很舒服，適合睡前慢慢看。",
    synopsis: "關於重逢，也關於那些沒有說出口的想念。",
  },
  {
    id: "b7",
    title: "星河之外",
    author: "陸舟",
    category: ["科幻"],
    wordCount: 960000,
    status: "dropped",
    dropChapter: "72",
    dropDate: "2026-08-20",
    dropReason: "設定有趣，但中段節奏較慢，暫時沒有繼續讀下去。",
    addDate: "2026-08-05",
    synopsis: "一艘來自百年前的飛船，再次傳回訊號。",
  },
  {
    id: "b8",
    title: "舊巷記事",
    author: "聽風",
    category: ["都市"],
    wordCount: null,
    status: "reading",
    addDate: "2026-08-01",
    synopsis: "巷子裡的每一道門，都藏著一個故事。",
  },
];
